"""Export artifacts for independent solvers, to cross-check our own engine.

Produces:
  <name>_behavioural.v   self-contained Verilog (no PDK needed)
  <name>_structural.v    standard-cell netlist (needs sky130 models)
  <name>_bmc.smt2        the unrolled BMC problem straight from our z3 solver
  <name>_yosys.ys        yosys script for its built-in `sat`
  <name>_smtbmc.ys       yosys script that writes SMT2 for yosys-smtbmc
  run_yosys.ps1 / .sh    runnable wrappers

WHAT THIS DOES AND DOES NOT PROVE.  Both Verilog files and the SMT2 are
generated FROM cells.py, so they share our model of what each standard cell
does.  Running them through yosys or an external SMT solver is therefore an
independent SOLVER check -- it can catch a bug in our z3 encoding, our
unrolling, or our search -- but it is NOT an independent CIRCUIT-MODEL check.
If cells.py had a cell wrong, every one of these artifacts would be wrong in
exactly the same way and they would all agree.

The only check that can catch a wrong cell model is
audit_cell_semantics.py, which compares cells.py against the SKY130 Liberty
data, a source we did not write.

NOTE: yosys is not installed in this environment, so the .ys scripts are written
from the documented command syntax but have not been executed here.  The SMT2
file and both Verilog files are generated by code that is exercised by the test
suite.

Usage: python scripts/export_solver.py recovered.json outdir/name --output success
"""

import argparse
import json
import os

import z3

import emit_behavioural
import emit_verilog
from sim import Circuit


def write_smt2(netlist_path, out_path, output, cycles, hold, reset_net,
               reset_cycles, reset_active_high):
    import solve_bmc

    cfg = solve_bmc.Config()
    cfg.output = output
    cfg.clock = "clk"
    cfg.reset_net = reset_net
    cfg.reset_cycles = reset_cycles
    cfg.reset_active_high = reset_active_high
    cfg.default = 0
    cfg.start_cycle = 0
    cfg.data = set()
    cfg.hold = hold
    cfg.pattern = {}
    cfg.group = {}
    cfg.charset = {}
    cfg.ranges = {}

    circuit = Circuit(json.load(open(netlist_path)))
    bmc = solve_bmc.IncrementalBMC(circuit, cfg)
    for _ in range(cycles):
        bmc.extend()
    bmc.s.add(bmc.success[cycles - 1] == True)
    with open(out_path, "w") as f:
        f.write(bmc.s.to_smt2())
        f.write("\n(check-sat)\n(get-model)\n")
    print(f"wrote {out_path} (depth {cycles}, "
          f"{len(bmc.assertions)} assertions)")


YOSYS_SAT = """# yosys built-in SAT solver, sequential mode.
# Independent cross-check of our z3 engine at the same depth.
read_verilog {vfile}
prep -top {top}
flatten
opt -full

# Hold reset asserted in the first cycle, then release it.
#   -set-at 1 {reset} {reset_assert}
#   -set-at 2 {reset} {reset_deassert}
# and require the target high at the final step.
sat -seq {depth} -set-init-zero \\
    -set-at 1 {reset} {reset_assert} \\
    -set-def-at 2 {reset} \\
    -set-at {depth} {output} 1 \\
    -show-inputs -show-outputs -dump_vcd {vcd}
"""

YOSYS_SMTBMC = """# Write an SMT2 transition system for yosys-smtbmc.
read_verilog {vfile}
prep -top {top}
flatten
opt -full
write_smt2 -wires {smt2}

# then run, outside yosys:
#   yosys-smtbmc -s z3 -t {depth} --dump-vcd {vcd} {smt2}
# add  --smtc constraints.smtc  to pin reset/enable per cycle.
"""

PS1 = """# Cross-check with yosys (must be installed and on PATH).
$ErrorActionPreference = "Stop"
yosys -s "{ys_sat}"
yosys -s "{ys_smtbmc}"
yosys-smtbmc -s z3 -t {depth} --dump-vcd "{vcd}" "{smt2}"
"""

SH = """#!/bin/sh
set -e
yosys -s "{ys_sat}"
yosys -s "{ys_smtbmc}"
yosys-smtbmc -s z3 -t {depth} --dump-vcd "{vcd}" "{smt2}"
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("netlist")
    ap.add_argument("prefix", help="output path prefix, e.g. generated/puzzle")
    ap.add_argument("--output", default="success")
    ap.add_argument("--depth", type=int, default=32)
    ap.add_argument("--reset-net", default="rst_n")
    ap.add_argument("--reset-cycles", type=int, default=1)
    ap.add_argument("--reset-active-high", action="store_true")
    ap.add_argument("--hold", action="append", default=[], metavar="NET=0|1")
    ap.add_argument("--skip-smt2", action="store_true")
    a = ap.parse_args()

    data = json.load(open(a.netlist))
    top = data.get("top", "recovered")
    hold = {}
    for h in a.hold:
        k, v = h.split("=")
        hold[k] = int(v)

    beh = f"{a.prefix}_behavioural.v"
    stru = f"{a.prefix}_structural.v"
    smt2 = f"{a.prefix}_bmc.smt2"
    ys_smt2 = f"{a.prefix}_yosys.smt2"
    ys_sat = f"{a.prefix}_yosys.ys"
    ys_bmc = f"{a.prefix}_smtbmc.ys"
    vcd = f"{a.prefix}_yosys.vcd"

    emit_behavioural.emit(data, beh, top)
    emit_verilog.emit(data, stru, top)

    if not a.skip_smt2:
        write_smt2(a.netlist, smt2, a.output, a.depth, hold, a.reset_net,
                   a.reset_cycles, a.reset_active_high)

    assert_lvl = 1 if a.reset_active_high else 0
    open(ys_sat, "w").write(YOSYS_SAT.format(
        vfile=os.path.basename(beh), top=top, depth=a.depth,
        output=a.output, reset=a.reset_net,
        reset_assert=assert_lvl, reset_deassert=1 - assert_lvl,
        vcd=os.path.basename(vcd)))
    open(ys_bmc, "w").write(YOSYS_SMTBMC.format(
        vfile=os.path.basename(beh), top=top, depth=a.depth,
        smt2=os.path.basename(ys_smt2), vcd=os.path.basename(vcd)))
    d = os.path.dirname(a.prefix) or "."
    open(os.path.join(d, "run_yosys.ps1"), "w").write(PS1.format(
        ys_sat=os.path.basename(ys_sat), ys_smtbmc=os.path.basename(ys_bmc),
        depth=a.depth, vcd=os.path.basename(vcd),
        smt2=os.path.basename(ys_smt2)))
    open(os.path.join(d, "run_yosys.sh"), "w").write(SH.format(
        ys_sat=os.path.basename(ys_sat), ys_smtbmc=os.path.basename(ys_bmc),
        depth=a.depth, vcd=os.path.basename(vcd),
        smt2=os.path.basename(ys_smt2)))

    print(f"wrote {ys_sat}, {ys_bmc}, run_yosys.ps1, run_yosys.sh")
    print("yosys is not installed here; those scripts are untested.")


if __name__ == "__main__":
    main()
